export type Language = 'en' | 'hi';

export const COPY = {
  en: {
    nav: {
      brand: 'ZeroGap',
      features: 'Features',
      howItWorks: 'How it works',
      faq: 'FAQ',
      tryDemo: 'Try the live demo',
      dashboard: 'Dashboard',
      sales: 'Sales → GSTR-1',
      purchases: 'Purchases vs 2B',
      triangle: 'Triangle Check',
      periods: 'Periods',
      reports: 'Reports',
      settings: 'Settings',
    },
    landing: {
      eyebrow: 'AI BUILDER CUP 2026 · BFSI',
      h1Line1: 'Zero gap.',
      h1Line2: 'Zero notice.',
      sub: 'Upload your bills. ZeroGap reads them, matches them against your GST data, and prepares your GSTR-1 — before the tax department finds a problem.',
      primaryCta: 'Try the live demo',
      secondaryCta: 'See how it works',
      trustStrip: 'Built on Google Cloud · Document AI + Gemini · Made for Indian small businesses',
      mockCard: {
        title: 'Tax credit at risk',
        amount: '₹1,84,200',
        subtitle: 'at risk across 14 mismatches',
        badge: 'ACTION NEEDED',
        whyPrompt: 'Why?',
        whyExplanation: '₹1,84,200 total ITC blocked because suppliers haven\'t uploaded or filed their GSTR-1 returns on time.',
      },
      featuresTitle: 'Four automated checks before you pay a single rupee in tax',
      featuresSub: 'Everything your CA checks manually at the end of the month, completed in seconds with Document AI and Gemini.',
      featureCards: [
        {
          id: 'f1',
          tag: 'FEATURE 1',
          icon: 'receipt',
          title: 'Bills in, GSTR-1 out.',
          desc: 'Drop PDF/photo sales bills. Document AI extracts line items, validates HSN codes against master rates, and compiles a portal-ready GSTR-1 JSON and Excel file.',
          stat: '24 bills parsed in 18s',
        },
        {
          id: 'f2',
          tag: 'FEATURE 2',
          icon: 'search',
          title: 'Find every rupee of credit you\'re losing.',
          desc: 'Reconcile purchase invoices against your official GSTR-2B download. Spot unfiled supplier bills before Rule 88D triggers a DRC-01C demand notice.',
          stat: '₹1,84,200 credit protected',
        },
        {
          id: 'f3',
          tag: 'FEATURE 3',
          icon: 'scale',
          title: 'Three numbers. Zero surprises.',
          desc: 'Compare GSTR-1 outward tax liability, GSTR-2B available ITC, and your GSTR-3B tax payment. Avoid costly automated department scrutiny.',
          stat: '100% Rule 88C/88D audit',
        },
        {
          id: 'f4',
          tag: 'FEATURE 4',
          icon: 'calendar',
          title: 'Month, quarter, year — one view.',
          desc: 'Historical period rollups powered by BigQuery. Track multi-month tax liabilities and ITC trends, directly feeding your annual GSTR-9 filing.',
          stat: 'Quarterly & FY Rollups',
        },
      ],
      howItWorksTitle: 'How ZeroGap works in four simple steps',
      howItWorksSub: 'No portal credentials needed. You stay in 100% control of your business data.',
      steps: [
        {
          num: '1',
          title: 'Upload bills',
          desc: 'Drag & drop your sales or purchase invoices in PDF, JPG, or PNG format, plus your GSTR-2B file.',
        },
        {
          num: '2',
          title: 'Review with AI',
          desc: 'Pretrained Document AI flags missing HSN digits, incorrect GST rates, and invalid GSTIN formats.',
        },
        {
          num: '3',
          title: 'Reconcile in 1-click',
          desc: 'Automated matching engine checks every invoice against 2B records and computes exact rupee impact.',
        },
        {
          num: '4',
          title: 'Export & File',
          desc: 'Download byte-exact GSTR-1 JSON ready for the official GST portal, plus audit-ready Excel reports.',
        },
      ],
      demoBand: {
        title: 'See a real reconciliation in 60 seconds.',
        cta: 'Watch demo walkthrough',
        tagline: 'Experience why Indian MSMEs and Chartered Accountants trust ZeroGap.',
      },
      faqTitle: 'Frequently asked questions',
      faqSub: 'Everything you need to know about ZeroGap, GST compliance, and data privacy.',
      faq: [
        {
          q: 'Do I need to give my GST password?',
          a: 'Never. You simply upload your invoice copies and downloaded GSTR-2B Excel or CSV files. ZeroGap never asks for or touches your official GST portal credentials.',
        },
        {
          q: 'Is my business data safe?',
          a: 'Yes. All data is processed and stored strictly in Google Cloud\'s asia-south1 (Mumbai) region with enterprise-grade encryption at rest and in transit.',
        },
        {
          q: 'What is Rule 88D and DRC-01C, and why do they matter?',
          a: 'Under Rule 88D, the GST system automatically compares ITC claimed in GSTR-3B with available credit in GSTR-2B. If you claim excess credit, a DRC-01C notice gives you only 7 days to pay or explain, otherwise your next GSTR-1 is blocked. ZeroGap flags these discrepancies before you file.',
        },
        {
          q: 'Who is ZeroGap built for?',
          a: 'ZeroGap is designed specifically for Indian small businesses (MSMEs, traders, manufacturers) and their practicing Chartered Accountants / tax consultants who want stress-free, accurate filing without expensive enterprise software.',
        },
      ],
      footer: {
        tagline: 'Zero gap. Zero notice.',
        team: 'Team JalebiJS · AI Builder Cup 2026 · BFSI Track',
        disclaimer: 'ZeroGap is an independent tax copilot built on Google Cloud. Not directly affiliated with GSTN or CBIC.',
      },
    },
    common: {
      moneyAtRisk: 'Tax credit at risk',
      cleanState: 'All clear — nothing needs your attention',
      whyAffordance: 'Why?',
      whatHappened: 'What happened',
      moneyInvolved: 'Money involved',
      whyItMatters: 'Why it matters',
      whatToDo: 'What to do',
      triangleDisclaimer: 'A gap is a question, not a verdict. Review the possible causes before deciding.',
      exportGateMessage: 'Fix the 3 red rows above (or tick \'I have checked\') to unlock the download.',
      explainInSimpleWords: 'Explain in simple words',
      downloadJson: 'Download JSON',
      downloadExcel: 'Download Excel',
      downloadPdf: 'Download PDF',
      copyForWhatsApp: 'Copy summary for WhatsApp',
      runMatch: 'Run match',
      generateGstr1: 'Generate GSTR-1',
      confirmAllGreen: 'Confirm all green rows',
      loadDemoData: 'Load demo data — 1 click',
      uploadBills: 'Upload my bills',
    },
  },
  hi: {
    nav: {
      brand: 'ZeroGap',
      features: 'सुविधाएं (Features)',
      howItWorks: 'यह कैसे काम करता है',
      faq: 'सवाल-जवाब (FAQ)',
      tryDemo: 'लाइव डेमो चलाएं',
      dashboard: 'डैशबोर्ड',
      sales: 'बिक्री → GSTR-1',
      purchases: 'खरीद बनाम 2B',
      triangle: 'त्रिकोण जांच (Triangle)',
      periods: 'मासिक/वार्षिक',
      reports: 'रिपोर्ट्स',
      settings: 'सेटिंग्स',
    },
    landing: {
      eyebrow: 'AI BUILDER CUP 2026 · BFSI',
      h1Line1: 'Zero gap.',
      h1Line2: 'Zero notice.',
      sub: 'अपने बिल अपलोड करें। ZeroGap उन्हें पढ़ता है, आपके GST डेटा से मिलाता है, और GSTR-1 तैयार करता है — इससे पहले कि टैक्स विभाग कोई नोटिस भेजे।',
      primaryCta: 'लाइव डेमो देखें',
      secondaryCta: 'कैसे काम करता है',
      trustStrip: 'Google Cloud पर निर्मित · Document AI + Gemini · भारतीय छोटे व्यवसायों के लिए',
      mockCard: {
        title: 'टैक्स क्रेडिट खतरे में (At Risk)',
        amount: '₹1,84,200',
        subtitle: '14 बिलों में गड़बड़ी मिली',
        badge: 'तुरंत ध्यान दें',
        whyPrompt: 'कारण?',
        whyExplanation: '₹1,84,200 का टैक्स क्रेडिट अटका हुआ है क्योंकि सप्लायर्स ने समय पर GSTR-1 दाखिल नहीं किया।',
      },
      featuresTitle: 'टैक्स चुकाने से पहले 4 ऑटोमैटिक जांच',
      featuresSub: 'जो काम आपका CA महीने के अंत में घंटों में करता है, वह कुछ ही सेकंड में AI द्वारा सुरक्षित रूप से पूरा करें।',
      featureCards: [
        {
          id: 'f1',
          tag: 'फीचर 1',
          icon: 'receipt',
          title: 'Bills in, GSTR-1 out.',
          desc: 'बिक्री बिल PDF या फोटो अपलोड करें। Document AI डेटा निकालता है, HSN कोड जांचता है, और पोर्टल-रेडी GSTR-1 फाइल बनाता है।',
          stat: '24 बिल 18 सेकंड में प्रोसेस',
        },
        {
          id: 'f2',
          tag: 'फीचर 2',
          icon: 'search',
          title: 'अटका हुआ एक-एक रुपया खोजें।',
          desc: 'खरीद बिलों को GSTR-2B से मिलाएं। सप्लायर के छूटे हुए बिलों को पहचानें और Rule 88D के तहत DRC-01C नोटिस से बचें।',
          stat: '₹1,84,200 सुरक्षित क्रेडिट',
        },
        {
          id: 'f3',
          tag: 'फीचर 3',
          icon: 'scale',
          title: 'तीन संख्याएं। शून्य हैरानी।',
          desc: 'GSTR-1, 2B और 3B के आंकड़ों की तुलना करें। टैक्स भरने से पहले सुनिश्चित करें कि कोई गैप न हो।',
          stat: '100% Rule 88C/88D ऑडिट',
        },
        {
          id: 'f4',
          tag: 'फीचर 4',
          icon: 'calendar',
          title: 'महीना, तिमाही, साल — एक नज़र में।',
          desc: 'BigQuery द्वारा संचालित ऐतिहासिक डेटा। GSTR-9 वार्षिक रिटर्न के लिए तैयार सारांश देखें।',
          stat: 'तिमाही और वार्षिक रोलअप',
        },
      ],
      howItWorksTitle: 'ZeroGap 4 आसान चरणों में काम करता है',
      howItWorksSub: 'कोई GST पासवर्ड देने की ज़रूरत नहीं। आपका डेटा पूरी तरह सुरक्षित।',
      steps: [
        {
          num: '1',
          title: 'बिल अपलोड करें',
          desc: 'अपने बिक्री या खरीद बिल (PDF/फोटो) और GSTR-2B फाइल ड्रैग और ड्रॉप करें।',
        },
        {
          num: '2',
          title: 'AI समीक्षा',
          desc: 'Google Document AI गलत HSN, गलत GST दर और अमान्य GSTIN तुरंत पकड़ता है।',
        },
        {
          num: '3',
          title: '1-क्लिक समाधान',
          desc: 'मैचिंग इंजन हर बिल की जांच करता है और वास्तविक रुपए का असर दिखाता है।',
        },
        {
          num: '4',
          title: 'एक्सपोर्ट और फाइलिंग',
          desc: 'GST पोर्टल पर अपलोड करने योग्य GSTR-1 JSON और ऑडिट-रेडी एक्सेल डाउनलोड करें।',
        },
      ],
      demoBand: {
        title: '60 सेकंड में असली समाधान देखें।',
        cta: 'डेमो वीडियो देखें',
        tagline: 'जानिए क्यों भारतीय व्यापारी और सीए ZeroGap पर भरोसा करते हैं।',
      },
      faqTitle: 'अक्सर पूछे जाने वाले सवाल',
      faqSub: 'ZeroGap, टैक्स नियम और डेटा सुरक्षा के बारे में जानकारी।',
      faq: [
        {
          q: 'क्या मुझे अपना GST पासवर्ड देना होगा?',
          a: 'बिल्कुल नहीं। आप केवल बिल और डाउनलोड की गई 2B फाइल अपलोड करते हैं। हम कभी पासवर्ड नहीं मांगते।',
        },
        {
          q: 'क्या मेरा व्यापारिक डेटा सुरक्षित है?',
          a: 'हाँ, सारा डेटा Google Cloud के मुंबई (asia-south1) डेटा सेंटर में उच्च स्तरीय सुरक्षा के साथ रहता है।',
        },
        {
          q: 'Rule 88D और DRC-01C क्या है?',
          a: 'नियम 88D के तहत अगर आप 2B से ज़्यादा क्रेडिट लेते हैं तो 7 दिन में DRC-01C नोटिस का जवाब देना होता है। ZeroGap इसे पहले ही रोक देता है।',
        },
        {
          q: 'यह किसके लिए उपयोगी है?',
          a: 'यह भारतीय छोटे व्यापारियों (MSME) और उनके चार्टर्ड एकाउंटेंट्स (CA) के लिए खास तौर पर बनाया गया है।',
        },
      ],
      footer: {
        tagline: 'Zero gap. Zero notice.',
        team: 'Team JalebiJS · AI Builder Cup 2026 · BFSI Track',
        disclaimer: 'ZeroGap एक स्वतंत्र टैक्स टूल है जो Google Cloud पर निर्मित है।',
      },
    },
    common: {
      moneyAtRisk: 'टैक्स क्रेडिट खतरे में (At Risk)',
      cleanState: 'सब कुछ सही है — कोई समस्या नहीं',
      whyAffordance: 'कारण?',
      whatHappened: 'क्या हुआ',
      moneyInvolved: 'रुपए का असर',
      whyItMatters: 'यह क्यों जरूरी है',
      whatToDo: 'क्या करना चाहिए',
      triangleDisclaimer: 'गैप एक सवाल है, अंतिम फैसला नहीं। निर्णय लेने से पहले सभी कारणों की समीक्षा करें।',
      exportGateMessage: 'डाउनलोड अनलॉक करने के लिए ऊपर की 3 लाल पंक्तियों को ठीक करें (या \'मैंने जांच लिया\' चुनें)।',
      explainInSimpleWords: 'सरल शब्दों में समझाएं',
      downloadJson: 'JSON डाउनलोड करें',
      downloadExcel: 'एक्सेल डाउनलोड करें',
      downloadPdf: 'PDF डाउनलोड करें',
      copyForWhatsApp: 'व्हाट्सएप के लिए कॉपी करें',
      runMatch: 'मैच शुरू करें',
      generateGstr1: 'GSTR-1 तैयार करें',
      confirmAllGreen: 'सभी सही बिल स्वीकार करें',
      loadDemoData: 'डेमो डेटा लोड करें — 1 क्लिक',
      uploadBills: 'बिल अपलोड करें',
    },
  },
} as const;
