import { getApps, getApp, initializeApp, cert, App } from 'firebase-admin/app';
import { getFirestore, Firestore } from 'firebase-admin/firestore';
import { CONFIG } from '@/lib/config';
import fs from 'fs';
import path from 'path';

// Initialize Firebase Admin SDK safely
function initAdmin(): App | null {
  const apps = getApps();
  if (apps.length > 0 && apps[0]) {
    return apps[0];
  }

  // Clear non-existent credentials path to avoid ENOENT errors in Google Auth
  if (process.env.GOOGLE_APPLICATION_CREDENTIALS && !fs.existsSync(process.env.GOOGLE_APPLICATION_CREDENTIALS)) {
    delete process.env.GOOGLE_APPLICATION_CREDENTIALS;
  }

  const projectId = process.env.GCP_PROJECT_ID || 'zerogap-509816';
  const serviceAccountPath = path.resolve(process.cwd(), 'service-account.json');

  if (fs.existsSync(serviceAccountPath)) {
    try {
      const serviceAccount = JSON.parse(fs.readFileSync(serviceAccountPath, 'utf8'));
      return initializeApp({
        credential: cert(serviceAccount),
        projectId: serviceAccount.project_id || projectId,
      });
    } catch (e) {
      console.warn('Failed parsing service-account.json, falling back to default:', e);
    }
  }

  try {
    return initializeApp({
      projectId: projectId,
    });
  } catch (e) {
    return null;
  }
}

const adminApp = initAdmin();

// In-memory cache/mock store for offline dev & instant demo reads
const memoryStore = {
  businesses: new Map<string, any>(),
  periods: new Map<string, any>(),
  jobs: new Map<string, any>(),
  invoices: new Map<string, any>(),
};

// Seed demo business & period in memory as guaranteed fallback
const DEMO_BIZ_ID = 'biz_sharma_traders_demo';
const DEMO_PERIOD = CONFIG.demo.periodCode; // '202609'

memoryStore.businesses.set(DEMO_BIZ_ID, {
  id: DEMO_BIZ_ID,
  name: CONFIG.demo.businessName,
  gstin: '06ABCDE1234F1Z5',
  turnoverSlab: 'UNDER_5CR',
  stateCode: '06',
  ownerUid: 'demo_user',
  createdAt: new Date().toISOString(),
});

memoryStore.periods.set(`${DEMO_BIZ_ID}_${DEMO_PERIOD}`, {
  id: DEMO_PERIOD,
  bizId: DEMO_BIZ_ID,
  period: DEMO_PERIOD,
  status: { f1: 'done', f2: 'done', f3: 'done' },
  totals: {
    salesTxval: CONFIG.demo.salesTaxableValue,
    salesTax: CONFIG.demo.salesTax,
    purchaseTxval: 1433100,
    itcAvailable2B: CONFIG.demo.itcAvailable2B,
    itcClaimed: CONFIG.demo.itcClaimed3B,
  },
  triangle: {
    liabilityGap: 0,
    itcGap: CONFIG.demo.creditCheckGap,
  },
  moneyAtRisk: CONFIG.demo.moneyAtRisk,
  matchScore: CONFIG.demo.matchScore,
  updatedAt: new Date().toISOString(),
});

// Seed 24 sales invoices for Sharma Traders (Demo)
function seedDemoInvoices() {
  const seedInvs = [
    {
      id: 'inv_demo_001',
      inum: 'INV-001',
      idt: '15-09-2026',
      ctin: '07ABCDE1234F1Z5',
      ctinName: 'Delhi Tech Labs Pvt Ltd',
      pos: '07',
      section: 'B2B',
      hsn: '8471',
      desc: 'Workstations & Peripherals',
      txval: 10000,
      rt: 18,
      iamt: 1800,
      camt: 0,
      samt: 0,
      status: 'green',
      docAiConfidence: 0.98,
      confidences: { inum: 0.99, idt: 0.98, ctin: 0.97, hsn: 0.98, txval: 0.99 },
    },
    {
      id: 'inv_demo_002',
      inum: 'INV-002',
      idt: '16-09-2026',
      ctin: '06BCDEF2345G2Z6',
      ctinName: 'Gurugram Systems LLP',
      pos: '06',
      section: 'B2B',
      hsn: '8517',
      desc: 'Network Routers & Hardware',
      txval: 25000,
      rt: 18,
      iamt: 0,
      camt: 2250,
      samt: 2250,
      status: 'green',
      docAiConfidence: 0.96,
      confidences: { inum: 0.98, idt: 0.97, ctin: 0.96, hsn: 0.95, txval: 0.98 },
    },
    {
      id: 'inv_demo_003',
      inum: 'INV-003',
      idt: '16-09-2026',
      ctin: '07CDEFG3456H3Z7',
      ctinName: 'Apex Data Services',
      pos: '07',
      section: 'B2B',
      hsn: '9983',
      desc: 'IT Infrastructure Consulting',
      txval: 40000,
      rt: 18,
      iamt: 7200,
      camt: 0,
      samt: 0,
      status: 'green',
      docAiConfidence: 0.95,
      confidences: { inum: 0.97, idt: 0.96, ctin: 0.95, hsn: 0.94, txval: 0.97 },
    },
    {
      id: 'inv_demo_004',
      inum: 'INV-004',
      idt: '17-09-2026',
      ctin: '',
      ctinName: 'Counter Cash Sale #1',
      pos: '06',
      section: 'B2CS',
      hsn: '8471',
      desc: 'Computer Accessories',
      txval: 5000,
      rt: 18,
      iamt: 0,
      camt: 450,
      samt: 450,
      status: 'green',
      docAiConfidence: 0.92,
      confidences: { inum: 0.95, idt: 0.94, hsn: 0.92, txval: 0.95 },
    },
    {
      id: 'inv_demo_005',
      inum: 'INV-005',
      idt: '17-09-2026',
      ctin: '06DEFGH4567J4Z8',
      ctinName: 'Panchkula Steel Works',
      pos: '06',
      section: 'B2B',
      hsn: '7326',
      desc: 'Fabricated Server Racks',
      txval: 15000,
      rt: 18,
      iamt: 0,
      camt: 1350,
      samt: 1350,
      status: 'green',
      docAiConfidence: 0.97,
      confidences: { inum: 0.98, idt: 0.97, ctin: 0.98, hsn: 0.96, txval: 0.98 },
    },
    {
      id: 'inv_demo_006',
      inum: 'INV-006',
      idt: '18-09-2026',
      ctin: '07EFGHI5678K5Z9',
      ctinName: 'Noida Software Hub',
      pos: '07',
      section: 'B2B',
      hsn: '8471',
      desc: 'Desktop Computer Units',
      txval: 30000,
      rt: 18,
      iamt: 5400,
      camt: 0,
      samt: 0,
      status: 'green',
      docAiConfidence: 0.94,
      confidences: { inum: 0.96, idt: 0.95, ctin: 0.94, hsn: 0.93, txval: 0.96 },
    },
    {
      id: 'inv_demo_007',
      inum: 'INV-007',
      idt: '18-09-2026',
      ctin: '07FGHIJ6789L6Z1',
      ctinName: 'Apex Infotech Solutions',
      pos: '07',
      section: 'B2B',
      hsn: '8471',
      desc: 'Storage Adapters & Peripherals',
      txval: 5000,
      rt: 12, // Billed 12%, usually 18%!
      iamt: 600,
      camt: 0,
      samt: 0,
      status: 'amber',
      flag: {
        code: 'RATE_MISMATCH',
        pillLabel: 'RATE?',
        message: 'Billed 12%, HSN 8471 usually 18% — check before filing',
      },
      docAiConfidence: 0.91,
      confidences: { inum: 0.95, idt: 0.94, ctin: 0.93, hsn: 0.91, txval: 0.94 },
    },
    {
      id: 'inv_demo_008',
      inum: 'INV-008',
      idt: '19-09-2026',
      ctin: '06GHIJK7890M7Z2',
      ctinName: 'Karnal Digital Store',
      pos: '06',
      section: 'B2B',
      hsn: '8517',
      desc: 'VoIP Telephony Equipment',
      txval: 20000,
      rt: 18,
      iamt: 0,
      camt: 1800,
      samt: 1800,
      status: 'green',
      docAiConfidence: 0.96,
      confidences: { inum: 0.97, idt: 0.96, ctin: 0.97, hsn: 0.95, txval: 0.97 },
    },
    {
      id: 'inv_demo_009',
      inum: 'INV-009',
      idt: '20-09-2026',
      ctin: '07HIJKL8901N8Z3',
      ctinName: 'Connaught Enterprise Corp',
      pos: '07',
      section: 'B2B',
      hsn: '8471',
      desc: 'Laser Printers & Scanners',
      txval: 35000,
      rt: 18,
      iamt: 6300,
      camt: 0,
      samt: 0,
      status: 'green',
      docAiConfidence: 0.97,
      confidences: { inum: 0.98, idt: 0.97, ctin: 0.97, hsn: 0.96, txval: 0.98 },
    },
    {
      id: 'inv_demo_010',
      inum: 'INV-010',
      idt: '21-09-2026',
      ctin: '06IJKLM9012P9Z4',
      ctinName: 'Faridabad Auto Tooling',
      pos: '06',
      section: 'B2B',
      hsn: '8443',
      desc: 'Commercial Print Spares',
      txval: 50000,
      rt: 18,
      iamt: 0,
      camt: 4500,
      samt: 4500,
      status: 'green',
      docAiConfidence: 0.95,
      confidences: { inum: 0.96, idt: 0.95, ctin: 0.95, hsn: 0.94, txval: 0.96 },
    },
    {
      id: 'inv_demo_011',
      inum: 'INV-011',
      idt: '21-09-2026',
      ctin: '07JKLMN0123Q1Z5',
      ctinName: 'South Ext Printers',
      pos: '07',
      section: 'B2B',
      hsn: '4820',
      desc: 'Continuous Computer Stationery',
      txval: 18000,
      rt: 18,
      iamt: 3240,
      camt: 0,
      samt: 0,
      status: 'green',
      docAiConfidence: 0.96,
      confidences: { inum: 0.97, idt: 0.96, ctin: 0.96, hsn: 0.95, txval: 0.97 },
    },
    {
      id: 'inv_demo_012',
      inum: 'INV-012',
      idt: '22-09-2026',
      ctin: '07KLMNO1234R2Z6',
      ctinName: 'Global Logistics Haryana',
      pos: '07',
      section: 'B2B',
      hsn: '996', // only 3 digits! Invalid HSN length
      desc: 'Express Courier & Handling',
      txval: 12000,
      rt: 18,
      iamt: 2160,
      camt: 0,
      samt: 0,
      status: 'red',
      flag: {
        code: 'HSN_INVALID_DIGITS',
        pillLabel: 'HSN?',
        message: 'HSN 996 has 3 digits. Min 4 digits required for turnover under ₹5cr.',
      },
      docAiConfidence: 0.89,
      confidences: { inum: 0.94, idt: 0.93, ctin: 0.94, hsn: 0.72, txval: 0.95 },
    },
    {
      id: 'inv_demo_013',
      inum: 'INV-013',
      idt: '22-09-2026',
      ctin: '06LMNOP2345S3Z7',
      ctinName: 'Panipat Fabrications',
      pos: '06',
      section: 'B2B',
      hsn: '9403',
      desc: 'Modular Workstation Tables',
      txval: 28000,
      rt: 18,
      iamt: 0,
      camt: 2520,
      samt: 2520,
      status: 'green',
      docAiConfidence: 0.94,
      confidences: { inum: 0.96, idt: 0.95, ctin: 0.96, hsn: 0.93, txval: 0.96 },
    },
    {
      id: 'inv_demo_014',
      inum: 'INV-014',
      idt: '23-09-2026',
      ctin: '07MNOPQ3456T4Z8',
      ctinName: 'Dwarka Cyber Technologies',
      pos: '07',
      section: 'B2B',
      hsn: '8471',
      desc: 'Server RAM & SSD Upgrades',
      txval: 22000,
      rt: 18,
      iamt: 3960,
      camt: 0,
      samt: 0,
      status: 'green',
      docAiConfidence: 0.98,
      confidences: { inum: 0.99, idt: 0.98, ctin: 0.98, hsn: 0.97, txval: 0.99 },
    },
    {
      id: 'inv_demo_015',
      inum: 'INV-015',
      idt: '23-09-2026',
      ctin: '06NOPQR4567U5Z9',
      ctinName: 'Hisar Industrial Spares',
      pos: '06',
      section: 'B2B',
      hsn: '8471',
      desc: 'Industrial Panel PC & Mounts',
      txval: 45000,
      rt: 18,
      iamt: 0,
      camt: 4050,
      samt: 4050,
      status: 'green',
      docAiConfidence: 0.97,
      confidences: { inum: 0.98, idt: 0.97, ctin: 0.98, hsn: 0.96, txval: 0.98 },
    },
    {
      id: 'inv_demo_016',
      inum: 'INV-016',
      idt: '24-09-2026',
      ctin: '07OPQRS5678V6Z1',
      ctinName: 'Janakpuri Communications',
      pos: '07',
      section: 'B2B',
      hsn: '8517',
      desc: 'Optical Fiber Modems',
      txval: 32000,
      rt: 18,
      iamt: 5760,
      camt: 0,
      samt: 0,
      status: 'green',
      docAiConfidence: 0.96,
      confidences: { inum: 0.97, idt: 0.96, ctin: 0.97, hsn: 0.95, txval: 0.97 },
    },
    {
      id: 'inv_demo_017',
      inum: 'INV-017',
      idt: '24-09-2026',
      ctin: '06PQRST6789W7Z2',
      ctinName: 'Rohtak Engineering Corp',
      pos: '06',
      section: 'B2B',
      hsn: '8471',
      desc: 'Enterprise Compute Rack',
      txval: 60000,
      rt: 18,
      iamt: 0,
      camt: 5400,
      samt: 5400,
      status: 'green',
      docAiConfidence: 0.97,
      confidences: { inum: 0.98, idt: 0.97, ctin: 0.98, hsn: 0.96, txval: 0.98 },
    },
    {
      id: 'inv_demo_018',
      inum: 'INV-018',
      idt: '25-09-2026',
      ctin: '07QRSTU7890X8Z3',
      ctinName: 'Saket Retail Chains Ltd',
      pos: '07',
      section: 'B2B',
      hsn: '8471',
      desc: 'Point-of-Sale Hardware Systems',
      txval: 125000,
      rt: 18,
      iamt: 22500,
      camt: 0,
      samt: 0,
      status: 'green',
      docAiConfidence: 0.98,
      confidences: { inum: 0.99, idt: 0.98, ctin: 0.98, hsn: 0.97, txval: 0.99 },
    },
    {
      id: 'inv_demo_019',
      inum: 'INV-019',
      idt: '25-09-2026',
      ctin: '07INVALIDGSTIN', // Invalid GSTIN!
      ctinName: 'Quick Traders Karol Bagh',
      pos: '07',
      section: 'B2B',
      hsn: '8471',
      desc: 'Compact Desktop PC',
      txval: 15000,
      rt: 18,
      iamt: 2700,
      camt: 0,
      samt: 0,
      status: 'red',
      flag: {
        code: 'GSTIN_INVALID',
        pillLabel: 'GSTIN?',
        message: 'Invalid GSTIN format "07INVALIDGSTIN". Must match GSTN pattern.',
      },
      docAiConfidence: 0.84,
      confidences: { inum: 0.95, idt: 0.94, ctin: 0.52, hsn: 0.91, txval: 0.94 },
    },
    {
      id: 'inv_demo_020',
      inum: 'INV-020',
      idt: '26-09-2026',
      ctin: '', // No GSTIN + inter-state ('08' Rajasthan) + > 2.5L => B2CL
      ctinName: 'Jaipur Heritage Palace (Unregistered Inter-state)',
      pos: '08',
      section: 'B2CL',
      hsn: '8471',
      desc: 'Complete Office Automation Package',
      txval: 260000,
      rt: 18,
      iamt: 46800,
      camt: 0,
      samt: 0,
      status: 'green',
      docAiConfidence: 0.98,
      confidences: { inum: 0.99, idt: 0.98, hsn: 0.97, txval: 0.99 },
    },
    {
      id: 'inv_demo_021',
      inum: 'INV-021',
      idt: '26-09-2026',
      ctin: '',
      ctinName: 'Walk-in Retail Buyer A',
      pos: '06',
      section: 'B2CS',
      hsn: '8471',
      desc: 'External USB Hard Drives',
      txval: 10000,
      rt: 18,
      iamt: 0,
      camt: 900,
      samt: 900,
      status: 'green',
      docAiConfidence: 0.93,
      confidences: { inum: 0.95, idt: 0.94, hsn: 0.93, txval: 0.95 },
    },
    {
      id: 'inv_demo_022',
      inum: 'INV-022',
      idt: '27-09-2026',
      ctin: '',
      ctinName: 'Walk-in Retail Buyer B',
      pos: '06',
      section: 'B2CS',
      hsn: '8471',
      desc: 'Wireless Keyboards & Mice',
      txval: 8000,
      rt: 18,
      iamt: 0,
      camt: 720,
      samt: 720,
      status: 'green',
      docAiConfidence: 0.94,
      confidences: { inum: 0.96, idt: 0.95, hsn: 0.94, txval: 0.96 },
    },
    {
      id: 'inv_demo_023',
      inum: 'INV-023',
      idt: '27-09-2026',
      ctin: '',
      ctinName: 'Walk-in Retail Buyer C',
      pos: '06',
      section: 'B2CS',
      hsn: '8517',
      desc: 'Wi-Fi Extenders & Cables',
      txval: 12000,
      rt: 18,
      iamt: 0,
      camt: 1080,
      samt: 1080,
      status: 'green',
      docAiConfidence: 0.95,
      confidences: { inum: 0.96, idt: 0.95, hsn: 0.94, txval: 0.96 },
    },
    {
      id: 'inv_demo_024',
      inum: 'INV-024',
      idt: '28-09-2026',
      ctin: '',
      ctinName: 'Walk-in Retail Buyer D',
      pos: '06',
      section: 'B2CS',
      hsn: '8471',
      desc: 'Computer Monitor 24-inch',
      txval: 7000,
      rt: 18,
      iamt: 0,
      camt: 630,
      samt: 630,
      status: 'green',
      docAiConfidence: 0.95,
      confidences: { inum: 0.97, idt: 0.95, hsn: 0.94, txval: 0.97 },
    },
  ];

  for (const inv of seedInvs) {
    const taxTotal = inv.iamt + inv.camt + inv.samt;
    const invDoc = {
      id: inv.id,
      bizId: DEMO_BIZ_ID,
      period: DEMO_PERIOD,
      kind: 'sales',
      inum: inv.inum,
      idt: inv.idt,
      ctin: inv.ctin,
      ctinName: inv.ctinName,
      pos: inv.pos,
      rchrg: 'N',
      invTyp: 'R',
      section: inv.section,
      items: [
        {
          num: 1,
          hsn: inv.hsn,
          desc: inv.desc,
          qty: 1,
          uqc: 'NOS',
          txval: inv.txval,
          rt: inv.rt,
          iamt: inv.iamt,
          camt: inv.camt,
          samt: inv.samt,
          csamt: 0,
        },
      ],
      totals: {
        txval: inv.txval,
        iamt: inv.iamt,
        camt: inv.camt,
        samt: inv.samt,
        csamt: 0,
        totalTax: taxTotal,
        grandTotal: inv.txval + taxTotal,
      },
      status: inv.status,
      flag: inv.flag || null,
      flags: inv.flag ? [inv.flag] : [],
      docAiConfidence: inv.docAiConfidence,
      confidences: inv.confidences,
      correctedByUser: false,
      confirmed: inv.status === 'green',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    memoryStore.invoices.set(inv.id, invDoc);
  }
}

seedDemoInvoices();

export { adminApp, memoryStore, DEMO_BIZ_ID, DEMO_PERIOD };

export function getFirestoreDb(): Firestore | null {
  try {
    if (!adminApp) return null;
    return getFirestore(adminApp);
  } catch (e) {
    return null;
  }
}
